### ISSUE TITLE
Argon stuck with flashing green light

### ISSUE THREAD

**Issue by QuinnFreedman** [nrobinson2000/po#18]
When I build and flash my Argon with po, I get no errors and the CLI reports a successful flash, but nothing seems to happen. The on-board LED is flashing green, which means it is [trying to connect to WiFi](https://docs.particle.io/tutorials/device-os/led/photon/#looking-for-internet).

I'm not sure if it isn't actually flashing despite the fact that I get `Firmware successfully flashed to argon on /dev/ttyACM0`, or if it did flash but it is just stuck looking for wifi despite the fact that I put it in `MANUAL` mode. I also tried disabling the wifi with `WiFi.off();` and `Particle.disconnect();` but it didn't do anything.

My `firmware/main.cpp` looks like this:

I'm just running `po argon build && po argon flash` but my LED isn't coming on and nothing is being printed to `po serial monitor`.

```cpp
#include "Particle.h"

int led = D7;

SYSTEM_MODE(MANUAL);

void setup() // Put setup code here to run once
{
    Serial.begin(115200);
    Serial.println("starting");

    pinMode(led, OUTPUT);
}

void loop() // Put code here to loop forever
{
    Serial.println("loop");
    digitalWrite(led, HIGH);
    
    delay(500);

    digitalWrite(led, LOW);
    delay(500);

}

```

**Comment by nrobinson2000** [comment]
Hi @QuinnFreedman, I'm sorry you're having some difficulties.

0. What Linux distro are you using?

Knowing more about your environment will help us find a solution quicker.

1. What version of deviceOS are you using on your Argon?

You can check with `po info`. You can list all available versions with `po versions`. For example: if you wanted to use v1.1.0 you could use `po config v1.1.0`. Since you're using particle mesh you should run `po setup-mesh` just in case.

2. Is the Argon the only Particle device connected to your computer?

You can list all connected Particle devices with `po ls`

3. Have you tried verifying that you have the right permissions to put the Argon in DFU mode?

By default, at the ending of `po install`, a udev rules file for Particle devices is created and you should be added to the `plugdev` group.

Can you try doing `ls -la /dev/ttyACM0`?

On my machine (Linux Mint 19.1) I get:

```
$ ls -la /dev/ttyACM0
crw-rw-rw- 1 root plugdev 166, 0 Jul 13 13:40 /dev/ttyACM0
```

4. Can you try using the official `particle serial monitor` instead? It will warn you if there is a permissions error.

Also, in the future, I'd strongly suggest creating projects with the official Workbench/CLI structure, which po conveniently supports. You can use `particle project create`

When building or flashing a project with the official structure you need to append `-beta` to the commands.

Example:

```
po argon flash-beta
```

You can also do all of the commands listed in the [Workbench Makefile](https://github.com/nrobinson2000/po/blob/master/share/particle.mk).

For example, if you wanted to flash user and deviceOS all in one command, you would do:

```
po argon run flash-all
```

Overall, I think the root cause of your issue is a permissions error, or the request to put the Argon into DFU mode is not going through.

You can try to put the Argon into DFU mode with:

```
po dfu open
```

If you can try opening the `particle serial monitor` that would be a good first step.

Thanks for using po-util.

**Comment by QuinnFreedman** [comment]
Thanks for your quick replay! I've tried to answer your questions here:

## Linux version:
```
OS: Ubuntu 19.04 x86_64
Host: MACH-WX9 M14
Kernel: 5.0.0-20-generic
Uptime: 51 mins
Packages: 2432 (dpkg), 8 (snap)
Shell: zsh 5.5.1
Resolution: 3426x2284
DE: GNOME 3.32.1
WM: GNOME Shell
WM Theme: Adapta
Theme: Adapta [GTK2/3]
Icons: Paper [GTK2/3]
Terminal: alacritty
CPU: Intel i7-8550U (8) @ 4.000GHz
GPU: Intel UHD Graphics 620
GPU: NVIDIA GeForce MX150
Memory: 3801MiB / 15820MiB
```

## Device-OS version
```
$ po info

Sat 13 Jul 2019 11:36:24 AM PDT

po-util version: 7.1.0

Firmware Versions:
Particle: release/stable
Duo: duo

DFU Baud Rate: 14400
Automatic Headers:

Last Platform: argon
Last Project:  /home/quinn/workspace/aev/sensor/particle/firmware
```
## Permission

```
$ ls -la /dev/ttyACM0
crw-rw-rw- 1 root plugdev 166, 0 Jul 13 11:38 /dev/ttyACM0
```

# 4 
```
$ particle serial monitor
Opening serial monitor for com port: "/dev/ttyACM0"
Serial monitor opened successfully:

```

Then it just hangs and never prints anything else.


```
$ po dfu open
```
returns immediately with exit code 0. Running `po flash` afterward isn't any different.

<hr>

I will try creating a new project with the official CLI and using po from there.

**Comment by QuinnFreedman** [comment]
As another note, I reset my Argon to factory state (using the MODE and RESET buttons) and then re-configured it with my phone and connected it to wifi. Now, it has a breathing magenta light.

When I flash with po, I get a fast blinking yellow light (indicating that it is being flashed) and then I go back to the blinking green light for a little while and then back to breathing magenta. 

So it seems like it is flashing but then my code isn't doing anything. It seems to be ignoring the manual mode and connecting to wifi anyway (the blinking green) and now that I've provided the password for wifi it is actually able to connect. The led-blinking and serial code isn't running either

**Comment by nrobinson2000** [comment]
What if you try flashing the project and deviceOS?

```
po argon run flash-all
```

**Comment by QuinnFreedman** [comment]
I'm not sure how to do that. I get:
```
$ po argon run flash-all
Invalid folder!
Please choose a Particle project.
```

I'm running it from the root folder of my project where I ran `po init`. It looks like this:

```
  particle
├──   bin
│  ├──   obj
│  │  └──   src
│  │     ├──   module_info.o
│  │     ├──   module_info.o.d
│  │     ├──   newlib_stubs.o
│  │     ├──   newlib_stubs.o.d
│  │     ├──   user_export.o
│  │     ├──   user_export.o.d
│  │     ├──   user_module.o
│  │     └──   user_module.o.d
│  ├──   particle-argon.bin
│  ├──   particle-argon.bin.crc_block
│  ├──   particle-argon.bin.no_crc
│  ├──   particle-argon.elf
│  ├──   particle-argon.hex
│  ├──   particle-argon.lst
│  └──   particle-argon.map
├──   ci
│  └──   travis.sh
├──   firmware
│  └──   main.cpp
├──   particle-argon.bin
└──   README.md

```

**Comment by nrobinson2000** [comment]
That command expects the project to be in the the official project structure, not the legacy structure.

Can you try creating a project with `particle project create`, copy your code into the `src` directory and then try the command?

**Comment by QuinnFreedman** [comment]
I tried that and ran into a different problem.

I ran `particle project create` in a new, separate directory and created a new project (looks like this):

```
  testproject
├──   project.properties
├──   README.md
└──   src
   └──   testproject.ino
```

but when I cd into `testproject` and run `po argon run flash-all` or `po argon flash-beta` I get

```
Already found a device in DFU mode!

make: /home/quinn/particle/particle.mk: No such file or directory
make: *** No rule to make target '/home/quinn/particle/particle.mk'.  Stop.

Building firmware failed! DFU closed.
```

I'm not sure where it's getting `~/particle`. I think that's maybe where I tried to install po but the only thing in there is `dft-util/`

**Comment by nrobinson2000** [comment]
It looks like the installation might be messed up. Could you paste the contents of your `~/.po-util/config` here?

If you want to do a fresh reinstall I’d suggest deleting your `~/.po-util/config` and running `po install` again.

**Comment by QuinnFreedman** [comment]
Re-installing po fixed that error. Now running `po argon run flash-all` builds the firmware for a very long time before finally giving the error:

```
/usr/local/gcc-arm/bin/../lib/gcc/arm-none-eabi/5.3.1/../../../../arm-none-eabi/bin/ld: cannot open linker script file module_user_memory.ld: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [../../../build/module.mk:235: /home/quinn/workspace/aev/sensor/test/testproject/target/testproject.elf] Error 1
make[2]: Leaving directory '/home/quinn/.po-util/src/particle/firmware/modules/argon/user-part'
make[1]: *** [makefile:86: /home/quinn/.po-util/src/particle/firmware/modules/argon/user-part/makefile] Error 2
make[1]: Leaving directory '/home/quinn/.po-util/src/particle/firmware/modules'
make: *** [/home/quinn/.po-util/src/particle.mk:50: flash-all] Error 2

Building firmware failed! DFU closed.

```

**Comment by QuinnFreedman** [comment]
So very weirdly building with the new `particle project create` failed (as above) but after it did, my board started flashing the LED from my *old* legacy project. Going back to that directory, my old project works now. So I guess my problem is fixed? Not really sure what happened
